version: 0.2
phases:
  install:
    commands:
      - npm install -g npx
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npx ssup ./dist
